version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - nebhale
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - nebhale
